name: Check Flutter Dependencies

on:
  schedule:
    - cron: "0 1 * * *" # Runs every day at 8:00 JKT
  workflow_dispatch: # Allows manual trigger

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Check for outdated Flutter packages
        env:
          PROJECT_NAME: Flutter Usecase Template
        run: |
          output=$(flutter pub outdated)
          echo "$output"
          echo "$output" > outdated_report.txt          
          upgradable_packages=$(awk '/direct dependencies:/ {flag=1; next} /^$/ {flag=0} flag' outdated_report.txt)
          echo "Updradable packages:"
          echo "$upgradable_packages"

          if [ -n "$upgradable_packages" ]; then
            echo "MESSAGE=⚠️ **$PROJECT_NAME** packages have updates available!\`\`\`$upgradable_packages\`\`\`" >> $GITHUB_ENV
          else
            echo "MESSAGE=✅ **$PROJECT_NAME** dependencies are up to date!" >> $GITHUB_ENV
          fi

      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "{{ MESSAGE }}"
